### ISSUE TITLE
flags ancient files as "should not exist" but should flag as "deprecated, can be deleted"

### ISSUE THREAD

**Issue by joeldcanfield** [wp-cli/checksum-command#100]
These files are flagged as "should not exist" but are, in fact, ancient-but-valid files, retained sometime in the last century for backward compatibility.

```
wp-atom.php
wp-commentsrss2.php
wp-feed.php
wp-pass.php
wp-rdf.php
wp-register.php
wp-rss.php
wp-rss2.php
```

Rather than simply flagging them as superfluous, a better message would be "deprecated, can be deleted" which will 
(1) properly prioritize the danger as 'low'; and 
(2) offer a better solution (deletion) rather than the user creating even more automation routines to ignore the false positives.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @joeldcanfield 

WP-CLI simply pulls file checksums from WordPress.org:

https://github.com/wp-cli/checksum-command/blob/fc06b875d851481eb5c5bab47237a590a7aceae1/src/Checksum_Core_Command.php#L81-L88

If WP-CLI finds files that aren't included in the API response, then it flags them with the "should not exist" message:

https://github.com/wp-cli/checksum-command/blob/fc06b875d851481eb5c5bab47237a590a7aceae1/src/Checksum_Core_Command.php#L114-L122

Unfortunately, WP-CLI has no knowledge of which files are "deprecated and can be deleted". If the WordPress.org API includes this data in the future, then we can update the message accordingly. Until then, "should not exist" is only message that WP-CLI can provide.
