### ISSUE TITLE
`Could not retrieve the checksums` still visible with `--skip-plugins=<plugin-name>`

### ISSUE THREAD

**Issue by kanlukasz** [wp-cli/checksum-command#101]
Hi,

I have premium external plugins. As we know, it is currently unable to check their checksums.

So there is a note:
`Warning: Could not retrieve the checksums for version x.x.x. of plugin advanced-custom-fields-pro, skipping.`

I would like to get rid of this message so I try to use:
`wp plugin verify-checksums --all --skip-plugins=advanced-custom-fields-pro`

After using this command, this warning still exists `Could not retrieve the checks....`

What i did wrong?

**Comment by swissspidy** [comment]
Thanks for opening this issue! There's indeed a slight misconception here.

`--skip-plugins` is what we call a [global parameter](https://make.wordpress.org/cli/handbook/references/config/) which works with all commands. It tells WP-CLI to skip loading (executing) a certain plugin when interacting with WordPress.

So it's not related to the `verify-checksums` command specifically.

What you're after (checking all plugins except one), can not be achieved with a single argument like this.

However, you could do something like this instead:

1. Grab a list of all installed plugins
2. Filter the list to exclude `advanced-custom-fields-pro`
3. Run `wp plugin verify-checksums <plugins>...` for the remaining plugins in the list

Related: #64

**Comment by danielbachhuber** [comment]
We could potentially add an `--exclude=<plugin>` argument, similar to `wp plugin update`.

**Comment by stoyan-g** [comment]
Hello there, I've submitted a PR, regarding the mentioned issue here https://github.com/wp-cli/checksum-command/pull/104. I would also suggest adding an argument for skipping specific files inside the plugins. This can cover a plugin config file or some sort of export file inside of the plugin directory. If you think that this will be a good feature, I can open a new issue and provide a PR.

**Comment by danielbachhuber** [comment]
> I would also suggest adding an argument for skipping specific files inside the plugins. This can cover a plugin config file or some sort of export file inside of the plugin directory. If you think that this will be a good feature, I can open a new issue and provide a PR.

Let's hold off on this for now.

**Comment by danielbachhuber** [comment]
🔨
