### ISSUE TITLE
Add `--version` param to `wp plugin verify-checksums`

### ISSUE THREAD

**Issue by semseysandor** [wp-cli/checksum-command#106]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

For `wp core verify-checksums` the `--version` option is available to specify WP core version.
This is very useful in a deploy (update) process to check if the codebase is on the expected version.
If verify returns success, then skip download and/or report no change, if verification fails then download the right (usually newer) version. So it's possible to create an idempotent process.

It would be great to apply this logic to plugins also!

**Describe the solution you'd like**

Adding a `--version` option to `plugin verify-checksums` where we could directly set the version not just getting that from the plugin.
Of course, this would make sense only if a single plugin is provided, but this can be handled by ignoring `--version` if `--all` or multiple plugins are passed in.

Note: I'm happy to submit a PR.

**Comment by danielbachhuber** [comment]
Sounds good 👍 

We support multiple positional arguments and `--version=<version>` with `wp plugin install`, so we can follow that as prior art.

**Comment by semseysandor** [comment]
I was just wondering about the chances of wanting to install (or verify) two different plugins that happens to have the same version. With `--all`, I believe, that chance gets close to zero... :)
But why not indeed? There _can_ be a use-case, so don't limit ourselves.
