### ISSUE TITLE
--include-root does not work

### ISSUE THREAD

**Issue by ramonfincken** [wp-cli/checksum-command#110]
## Bug Report

- [x ] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x ] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**
wp-cli --allow-root core verify-checksums --include-root
Error: Parameter errors:
 unknown --include-root parameter

wp-cli --allow-root --include-root core verify-checksums
Error: Parameter errors:
 unknown --include-root parameter

same for
wp-cli --allow-root core --include-root verify-checksums

**Describe how other contributors can replicate this bug**
see above

**Comment by danielbachhuber** [comment]
Hey @ramonfincken,

Thanks for the report! `--include-root` will be available in the next released version of WP-CLI (v2.8.0). If you'd like to use it before then, you can upgrade to the latest nightly: `wp cli update --nightly`
