### ISSUE TITLE
Correctly use "installation" instead of "install"

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/checksum-command#18]
As per https://github.com/wp-cli/wp-cli/issues/4541, the documentation and success/error messages should use the full noun "installation".

**Comment by danielbachhuber** [comment]
@swissspidy I don't think it's necessary to create new issues in each repo. We can use that base issue to track, and submit pull requests against each repo.

**Comment by swissspidy** [comment]
I thought I'd create an issue here that I can reference in a PR but sure that works :)
