### ISSUE TITLE
Bumping supported version

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/checksum-command#22]
When a plugin author bumps supported core version in readme.txt we get "Checksum does not match"

**Comment by shawnhooper** [comment]
+1  My test results are returning Checksum does not match on 3 plugins' readme.txt files.

**Comment by danielbachhuber** [comment]
@szepeviktor @shawnhooper Can you share which plugins are impacted by this?

@schlessera Maybe we should only `Warning:` when `readme.txt` differs?

**Comment by szepeviktor** [comment]
> Maybe we should only Warning: when readme.txt differs?

Yes.

If a plugin author knows of this *trick* then readme will change outside of releases.

**Comment by szepeviktor** [comment]
> Can you share which plugins are impacted by this?

For example `wp-postratings`

**Comment by shawnhooper** [comment]
> Can you share which plugins are impacted by this?

`advanced-custom-fields`, `duplicate-post`, and `google-drive-embedder` on the site I tested with.

**Comment by schlessera** [comment]
@eriktorsner had included the concept of "soft changes" in his implementation: https://github.com/eriktorsner/wp-checksum/blob/6ed1a5ea5fb77f418a4abaf27795626ade75c863/src/PluginChecker.php#L22-L24

I'd suggest using the same approach, ignoring soft changes, while optionally allowing strict checks through an additional parameter.

**Comment by schlessera** [comment]
The "soft change" functionality was now added.

`readme.txt` changes should now be ignored unless you specify the `--strict` flag.

**Comment by szepeviktor** [comment]
https://github.com/wp-cli/checksum-command/commit/b4f07856db9fb644bb997e7751f161e03e3cd89e

Thank you.
