### ISSUE TITLE
checksum plugin not working for filenames with spaces

### ISSUE THREAD

**Issue by KrisShannon** [wp-cli/checksum-command#23]
I got these two lines from the `wp checksum plugin` command:

```
| hummingbird-performance | externals/shared-ui/font/WPMU                    | File is missing         |
| hummingbird-performance | externals/shared-ui/font/WPMU DEV Dashboard.json | File was added          |
```

I downloaded the zip file to make sure and `externals/shared-ui/font/WPMU DEV Dashboard.json` was in the zip file and there was no `externals/shared-ui/font/WPMU`

**Comment by KrisShannon** [comment]
I've just looked at https://downloads.wordpress.org/plugin-checksums/hummingbird-performance/1.7.0.3.json and it has the wrong information so this actually looks like an issue with the checksum generation process:

```
    "externals/shared-ui/font/WPMU": {
      "md5": "c4776ecd274631672894de248cfcf781",
      "sha256": "4893e60fe70682a9ad09b7ea9f95e44b60839dbd0bb3666ed05ce6ae0dbb2cce"
    },
```

**Comment by KrisShannon** [comment]
I think the problem is in the [WordPressdotorg\Plugin_Directory\Zip\Builded::generate_checksums inner foreach loop](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/plugin-directory/zip/class-builder.php?rev=6184#L218):

```php
foreach ( $checksum_output as $line ) {
    list( $checksum, $filename ) = preg_split( '!\s+!', $line );
    $filename = trim( preg_replace( '!^./!', '', $filename ) );
    $checksum = trim( $checksum );
```

That `preg_split` should be `preg_split( '!\s+!', $line, 2 )`

**Comment by KrisShannon** [comment]
I've submitted a Ticket [#3335](https://meta.trac.wordpress.org/ticket/3335) at meta.trac.wordpress.org

**Comment by schlessera** [comment]
Yes, I can confirm that this looks like an upstream bug.

Thanks for the thorough report and the meta patch you submitted!

**Comment by KrisShannon** [comment]
Ticket [#3335](https://meta.trac.wordpress.org/ticket/3335) has been closed and it looks like it's working.   The [checksums](https://downloads.wordpress.org/plugin-checksums/weblizar-pinterest-feeds/1.1.0.json) for [plugin weblizar-pinterest-feeds version 1.1.0](https://downloads.wordpress.org/plugin/weblizar-pinterest-feeds.1.1.0.zip) include the file "options/theme/pin-includes/pinterest_feed_api - Copy.php" (which is probably a plugin packaging mistake but it still proves the new code works)

**Comment by schlessera** [comment]
Yes, I can confirm as well, works as expected now.

Thanks again for the good work, @KrisShannon !
