### ISSUE TITLE
Soft changes need to be more flexible

### ISSUE THREAD

**Issue by schlessera** [wp-cli/checksum-command#34]
The soft change detection currently only works for the file `readme.txt` (case-sensitive): https://github.com/wp-cli/checksum-command/blob/master/src/Checksum_Plugin_Command.php#L339-L345

This detection needs to be more flexible, to cover all case variations as well as different endings (`.md`).

See https://github.com/wp-cli/wp-cli/issues/4681

**Comment by emirpprime** [comment]
Attempted fix #41 
- allow .md
- case insensitivity in filenames

**Comment by emirpprime** [comment]
Repeated PR with working tests #43

**Comment by schlessera** [comment]
Fixed via #43
