### ISSUE TITLE
Missing wp-cli/core-command dependency?

### ISSUE THREAD

**Issue by chesio** [wp-cli/checksum-command#53]
Hi,

I have a Composer-managed project, so I require only WP-CLI commands that I need for the project:
```
  "wp-cli/db-command": "^2.0",
  "wp-cli/entity-command": "^2.0",
  "wp-cli/checksum-command": "^2.0"
```

However, when I run `./vendor/bin/wp core verify-checksums`, I get:
```
Error: 'core' is not a registered wp command. See 'wp help' for available commands.
```

Shouldn't `wp-cli/core-command` be a dependency, when the `core` command is required for `verify-checksums` to run?

**Comment by schlessera** [comment]
The `core` command is not required, but the way we're currently conditionally using `WP_CLI::add_command()` breaks here.

We'd need to use a command namespace for core instead to solve this.

**Comment by schlessera** [comment]
@chesio The freshly tagged v2.0.1 will solve this issue. Just run `composer update wp-cli/checksum-command` and you should be good to go.
