### ISSUE TITLE
Can't save the output

### ISSUE THREAD

**Issue by NicolasKulka** [wp-cli/checksum-command#65]
Hello,

Command : 'wp core verify-checksums'

It is impossible for me to recover the return of this order, it is directly displayed.

Output with choice of format for example, same as commande 'wp plugin verify-checksums'

Do you have an idea to solve this problem?

**Comment by nateinaction** [comment]
There has been some discussion on this topic in #47

**Comment by R33D3M33R** [comment]
A workaround for your problem would be redirecting STDERR to STDOUT by using:

`wp core verify-checksums 2>&1`

This will then enable you to manipulate output.

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/wp-cli/checksum-command/issues/47
