### ISSUE TITLE
WordPress installation doesn't verify against checksums

### ISSUE THREAD

**Issue by Grafs** [wp-cli/checksum-command#70]
Download last version WordPress 
Upload to server by FTP
Upgrade database

Run command:
wp core verify-checksums
Warning: File doesn't verify against checksum: license.txt
Warning: File doesn't verify against checksum: wp-includes/images/crystal/license.txt
Error: WordPress installation doesn't verify against checksums.

Why a mistake?

**Comment by chesio** [comment]
Hi,

These two files are problematic, because unlike other files in WordPress distribution they have Windows line endings (CRLF). So if at any step of your deployment process the line endings have been converted to Unix line endings (LF), checksums will not match anymore.

**Comment by Grafs** [comment]
But I did not edit these files. Only upload by FTP.
If added (CRLF) in the uploaded files, why only these?

**Comment by Grafs** [comment]
Yes, thanks
In WinSCP setting, changing  Environment: CL to CL/RF and upload again.
Success: WordPress installation verifies against checksums.
