### ISSUE TITLE
Improve checksum-command short description

### ISSUE THREAD

**Issue by ako80218** [wp-cli/checksum-command#8]
Improve short description in https://github.com/wp-cli/checksum-command/src/Checksum_Command.php

wp checksum | Verify WordPress core checksums.

Proposed:
Compares the site’s core files with core at WordPress.org (via checksums).
cc: @hearvox

**Comment by schlessera** [comment]
`wp checksum core` is the command that verifies the core checksums.
`wp checksum` is a root command that is meant to get future additions like `wp checksum plugin` or `wp checksum theme`.

**Comment by danielbachhuber** [comment]
Handled in #11
