### ISSUE TITLE
Random messages: Could not retrieve the checksums for version x.y.z of plugin-name

### ISSUE THREAD

**Issue by R33D3M33R** [wp-cli/checksum-command#91]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Dear developers,

since a week or two the plugin checksum command has been behaving erratically. It displays "Could not retrieve the checksums for version x.y.z of plugin-name" for a lot of plugins. The set of plugins that can't be checked seems to be random - if you rerun it, some other plugins can't be retrieved. I can reproduce the problem on two different servers, PHP 7.4/8.0. 

**Describe how other contributors can replicate this bug**

```bash
wp plugin verify-checksums --all --path="/path/to/wp"
```

**Let us know what environment you are running this on**

```
OS:     Linux 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.3
php.ini used:   /etc/php/7.4/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.3.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/user
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.6.0

```

**Provide a possible solution**

I believe that the https://downloads.wordpress.org/plugin-checksums/ API limits have been changed and the script is now hitting into "429 Too Many Requests" error.

Best regards,
Andrej

**Comment by danielbachhuber** [comment]
> I believe that the https://downloads.wordpress.org/plugin-checksums/ API limits have been changed and the script is now hitting into "429 Too Many Requests" error.

@R33D3M33R Do you know how often your machine is hitting the plugin checksums API?

**Comment by danielbachhuber** [comment]
@lotsofbytes Do you know how often your machine is hitting the plugin checksums API? How many sites are you checking, how many plugins does each site have, and how often does your script run?

**Comment by lotsofbytes** [comment]
My client has a aws ec2 that hosts 8 wp sites. A cron job script loops the sites and veryfies wp core and plugins.
The job runs only once a day.

The total number of plugins are 120. Here is the breakdown of the number of plugins for the sites.

Error: Only verified 12 of 14 plugins (1 failed, 1 skipped).
Error: Only verified 16 of 18 plugins (1 failed, 1 skipped).
Error: Only verified 37 of 45 plugins (7 failed, 1 skipped).
Error: Only verified 6 of 7 plugins (1 failed).
Error: Only verified 10 of 11 plugins (1 failed).
Error: Only verified 9 of 10 plugins (1 failed).
Error: Only verified 7 of 10 plugins (2 failed, 1 skipped).
Error: Only verified 7 of 8 plugins (1 failed).

I have added a 30 sec. sleep in the loop recently. It reduced the number of warnings but it still gets a coup of warnings of the checksum retrieval failure.

Thanks.

**Comment by danielbachhuber** [comment]
Thanks for the additional details, @lotsofbytes.

I suspect the rate-limiting logic changed at some point. I've posed the question to the #meta channel in Slack: https://wordpress.slack.com/archives/C02QB8GMM/p1659451832035669

**Comment by dd32** [comment]
Some changes to rate-limits have been made, can anyone affected see if this is now resolved for them?

**Comment by lotsofbytes** [comment]
Thanks.
It's working, no warnings anymore!

**Comment by danielbachhuber** [comment]
@lotsofbytes Great, glad to hear!
