### ISSUE TITLE
Add --format argument to `wp core verify-checksums`

### ISSUE THREAD

**Issue by thend20** [wp-cli/checksum-command#94]
`wp plugin verify-checksums` already supports `--format`.  `wp core verify-checksums` should too.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @thend20 !

> `wp core verify-checksums` should too.

Could you share a bit more detail on how you might expect this to work?

**Comment by alaminfirdows** [comment]
@danielbachhuber Are you still maintaining this repo?

Any plans to add support for the `--format` parameter?

I’m open to implementing it and submitting a PR. Would you be willing to make a plan for it?

**Comment by alaminfirdows** [comment]
@ernilambar could you please take a look?
